  lane :test do

    # Ignores some frameworks, some cocoapods generated xccoonfig files and other resource files. Besides that it ignores the test target 

    lostFiles = itargetchecker(project_path:"../your_project.xcodeproj", 
                    ignore_files:["\w*\.framework\b*", "\w*\.xcconfig\b*", "\w*\.h\b*", "Info.plist"],
                    ignore_targets:["your_projectTests"])
    
    if lostFiles.count > 0
      UI.message "UPSY #{lostFiles}"
    else
      UI.message "Yahooo"
    end

  end
